#!/usr/bin/env bash
The OSI model is a model that characterizes the communication functions 
of a telecommunication system with a strong regard of 
their underlying internal structure and technology.

The OSI model is organized from the lowest to the highest

