#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
#Must show all processes, for all users, including those that dont have a TTY
#Display in a user-oriented format and show process hierarchy
ps aux
