#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

PID_FILE="/var/run/myscript.pid"

create_pid_file() {
    echo "$$" > "$PID_FILE"
}

cleanup() {
    echo "Cleaning up..."
    rm "$PID_FILE"
    exit
}

display_hate_message() {
    echo "I hate the kill command"
}

display_no_love_message() {
    echo "Y U no love me?!"
}

# Register signal handlers
trap cleanup EXIT
trap 'display_hate_message' SIGTERM
trap 'display_no_love_message' SIGINT

create_pid_file

while :
do
    echo "To infinity and beyond"
    sleep 2
done
