#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid

handle_sigquit() {
    rm /var/run/myscript.pid
    exit
}

handle_sigterm() {
    echo "I hate the kill command"
}

handle_sigint() {
    echo "Y U no love me?!"
}

# Register signal handlers
trap 'handle_sigquit' EXIT
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT

while :
do
    echo "To infinity and beyond"
    sleep 2
done
