#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/myscript.pid

handle_sigterm()
{
    echo "I hate the kill command"
}

handle_sigint()
{
    echo "Y U no love me?!"
}

trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT

while :
do
    echo "To infinity and beyond"
done

pkill -f -SIGKILL /var/run/myscript.pid
