#!/usr/bin/env bash
# manages manage_my_process
# Starts manage_my_process
# Creates a file containing its PID in /var/run/my_process.pid
# Displays manage_my_process started
# Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Displays manage_my_process stopped
# Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Starts manage_my_process
# Creates a file containing its PID in /var/run/my_process.pid
# Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} 
# if any other argument or no argument is passed

if [ $# -gt 0 ]; then
    case "$1" in
        start)
            if [ -f /var/run/my_process.pid ] && kill -0 "$(cat /var/run/my_process.pid)" 2>/dev/null; then
                echo "manage_my_process is already running"
            else
                ./manage_my_process &
                echo "$!" > /var/run/my_process.pid
                echo "manage_my_process started"
            fi
            ;;
        stop)
            if [ -f /var/run/my_process.pid ]; then
                echo "manage_my_process stopped"
                kill "$(cat /var/run/my_process.pid)"
                rm -f /var/run/my_process.pid
            else
                echo "manage_my_process is not running"
            fi
            ;;
        restart)
            if [ -f /var/run/my_process.pid ] && kill -0 "$(cat /var/run/my_process.pid)" 2>/dev/null; then
                kill "$(cat /var/run/my_process.pid)"
                rm -f /var/run/my_process.pid
            fi
            ./manage_my_process &
            echo "$!" > /var/run/my_process.pid
            echo "manage_my_process restarted"
            ;;
        *)
            echo "Usage: manage_my_process {start|stop|restart}"
            ;;
    esac
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
