#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# script should only display:username, user id and Home directory path for the user

# Use IFS (Internal Field Separator) to read ':' separated fields from /etc/passwd
while IFS=':' read -r line; do
    echo "$line" | cut -d':' -f1,3,6
done < /etc/passwd
