#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
# Do not display hidden files
for i in *; do
    if [[ "$i" == *-* ]]; then
        remove_first_dash="${i#*-}"
        echo "$remove_first_dash"
    fi
done
