#!/usr/bin/env bash
# resolve localhost anfd facebook 
cp /etc/hosts ~/hosts.new
sed -i s/127.*$/127.0.0.2 localhost/ hosts.new
sed -i s/127.*/8.8.8.8  facebook.com/ hosts.new
cp -f ~/hosts.new /etc/hosts
